log_level                :info
log_location             STDOUT
node_name                'admin'
client_key               '/home/maxim/chef-repo/.chef/admin.pem'
validation_client_name   'maxcorp-validator'
validation_key           '/home/maxim/chef-repo/.chef/maxcorp-validator.pem'
chef_server_url          'https://chef-server.example.com/organizations/maxcorp'
syntax_check_cache_path  '/home/maxim/chef-repo/.chef/syntax_check_cache'
cookbook_path		 '/home/maxim/chef-repo/cookbooks'
cookbook_copyright 	 'Maxcorp'
cookbook_license	 'apachev2'
cookbook_email 		 'makssych@gmail.com'
